output_dir: ~/scratch/experiments/

dataset:
  class: IndWN18RR
  root: ~/datasets/knowledge_graphs/
  version: {{ version }}

model:
  class: TAGNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  degree_msgs: no
  bias: yes
  drop: 0.45
  
task:
  num_negative: 1024
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [hits@10, hits@10_50]

optimizer:
  class: Adam
  lr: 5.0e-3
  weight_decay: 8.0e-5

train:
  gpus: {{ gpus }}
  batch_size: 32
  num_epoch: 16
  log_interval: 100
  decay: 0.9
  val_every: 1