output_dir: ~/experiments/

dataset:
  class: FB15k-237
  root: ~/datasets/knowledge_graphs/

model:
  class: DistNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  boundary_condition: yes
  bias: no
  drop: 0.40

task:
  num_negative: 2048
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-3
  weight_decay: 1.0e-7

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: 20
  log_interval: 100
  decay: 0.9
  val_every: 2