output_dir: ~/experiments/

dataset:
  class: WN18RR
  root: ~/datasets/knowledge_graphs/

model:
  class: TAGNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  concat_hidden: no
  short_cut: yes
  layer_norm: yes
  dependent: no
  bias: no
  weight_delta: yes
  att_type: score
  
task:
  num_negative: 128
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-3
  weight_decay: 1.0e-6

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: 20
  log_interval: 100
  decay: 0.9